Add a section on Extensible Priorities
kazuho/draft-kazuho-httpbis-priority pull request #104
Opened 2019-11-19 08:39 UTC by ianswett

With an initial set of text.

2019-11-19 08:50 UTC, LPardue requested changes

2019-11-19 08:50 UTC, LPardue commented on draft-kazuho-httpbis-priority.md
> +Care must be taken to ensure any use of extisting parameters are either
```suggestion
Care must be taken to ensure any use of existing parameters are either
```

2019-11-19 08:50 UTC, LPardue commented on draft-kazuho-httpbis-priority.md
> +Care must be taken to ensure any use of extisting parameters are either
I think the paragraph would also benefit from starting with the subject e.g. "When attempting to extend priorities, care must be taken.."

2019-11-19 08:52 UTC, LPardue approved these changes
This is a good starting point, I suggest we merge it as-is in order to permit further progress.

2019-11-19 08:53 UTC, merged

2019-11-20 01:29 UTC, kazuho commented
Thank you for the text. I think that the clarification on extensibility is fine.

OTOH, this looks to me like an in-progress work of refactoring being merged.

The previous structure of the document was to first describe the header and the parameters, then state that the frame reuses that encoding.

This PR changed the structure to first describe that SH is used by headers and frame, then talk about the header field along with and parameters, then talk separately about frames.

I think we should either restore the original structure (requires minimal work), or go ahead and refactor the text so that we discuss parameters in a conveyer-independent way, then talk about headers and frames.

2019-11-20 01:33 UTC, LPardue commented
I'll take the blame here. I think a few people would appreciate a document restructure in order to make changes that are more content full and accurate

2019-11-20 01:33 UTC, ianswett commented
I was going to do the latter ("go ahead and refactor the text so that we discuss parameters in a conveyer-independent way, then talk about headers and frames.") this afternoon after outstanding PRs are merged.

2019-11-20 02:17 UTC, kazuho commented
I share the view that restructuring is preferable.